function [u_exact,rhs,c0,BC,IBC] = DtNTest1(k)


c0 = @(x,y) zeros(size(x));
u_exact = @(x,y) sin(k*pi*x-0.1).*sin(k*pi*y-0.2);
du_exactdx = @(x,y) k*pi*cos(k*pi*x-0.1).*sin(k*pi*y-0.2);
du_exactdy = @(x,y) k*pi*sin(k*pi*x-0.1).*cos(k*pi*y-0.2);
rhs = @(x,y) 2*(k*pi)^2*sin(k*pi*x-0.1).*sin(k*pi*y-0.2);
BC = {@(x,y) u_exact(x,y),...
      @(x,y) u_exact(x,y),...
      @(x,y) u_exact(x,y),...
      @(x,y) u_exact(x,y),...
      @(x,y) u_exact(x,y)};
eta = k;
IBC = {@(x,y) -du_exactdx(x,y) + 1i*eta*u_exact(x,y),...
       @(x,y)  du_exactdx(x,y) + 1i*eta*u_exact(x,y),...
       @(x,y) -du_exactdy(x,y) + 1i*eta*u_exact(x,y),...
       @(x,y)  du_exactdy(x,y) + 1i*eta*u_exact(x,y)};

end