function [u_exact,rhs,c0,BC,IBC] = DtNTest2(k)

bump = @(x,y) -1.5 * exp(-160. * ((x-0.5).^2 + (y-0.5).^2));
c0 = @(x,y) -k^2*(1.0-bump(x,y));
u_exact = @(x,y) sin(8*pi./(x+y+pi/5));
du_exactdx = @(x,y) -8*pi ./ (x+y+pi/5).^2 .* cos(8*pi ./ (x+y+pi/5));
du_exactdy = @(x,y) -8*pi ./ (x+y+pi/5).^2 .* cos(8*pi ./ (x+y+pi/5));
rhs = @(x,y) ...
    -  32*pi.*cos(8*pi./(x+y+pi/5))./(x+y+pi/5).^3 ...
    + 128*pi^2*sin(8*pi./(x+y+pi/5))./(x+y+pi/5).^4 + + c0(x,y) .* u_exact(x,y);
BC = {@(x,y) u_exact(x,y),...
      @(x,y) u_exact(x,y),...
      @(x,y) u_exact(x,y),...
      @(x,y) u_exact(x,y),...
      @(x,y) u_exact(x,y)};
eta = k;
IBC = {@(x,y) -du_exactdx(x,y) + 1i*eta*u_exact(x,y),...
       @(x,y)  du_exactdx(x,y) + 1i*eta*u_exact(x,y),...
       @(x,y) -du_exactdy(x,y) + 1i*eta*u_exact(x,y),...
       @(x,y)  du_exactdy(x,y) + 1i*eta*u_exact(x,y)};

end