function [u_exact,rhs,c0,BC,poincareSteklovOperator,IBC,OBC,DBC] = DtNTest1(k)

c0 = @(x,y) zeros(size(x));
u_exact = @(x,y) sin(k*pi*x-0.1).*sin(k*pi*y-0.2);
BC = {@(x, y) u_exact(x,y),...
      @(x, y) u_exact(x,y),...
      @(x, y) u_exact(x,y),...
      @(x, y) u_exact(x,y),...
      @(x, y) u_exact(x,y)};
rhs = @(x,y) 2*(k*pi)^2*sin(k*pi*x-0.1).*sin(k*pi*y-0.2);

eta = k;

IBC = { ...
    @(x,y) (-k*pi*cos(k*pi*x-0.1).*sin(k*pi*y-0.2)) + 1i*eta*(sin(k*pi*x-0.1).*sin(k*pi*y-0.2)); ...
    @(x,y) (+k*pi*cos(k*pi*x-0.1).*sin(k*pi*y-0.2)) + 1i*eta*(sin(k*pi*x-0.1).*sin(k*pi*y-0.2)); ...
    @(x,y) (-k*pi*sin(k*pi*x-0.1).*cos(k*pi*y-0.2)) + 1i*eta*(sin(k*pi*x-0.1).*sin(k*pi*y-0.2)); ...
    @(x,y) (+k*pi*sin(k*pi*x-0.1).*cos(k*pi*y-0.2)) + 1i*eta*(sin(k*pi*x-0.1).*sin(k*pi*y-0.2)) ...
};

OBC = { ...
    @(x,y) (-k*pi*cos(k*pi*x-0.1).*sin(k*pi*y-0.2)) - 1i*eta*(sin(k*pi*x-0.1).*sin(k*pi*y-0.2)); ...
    @(x,y) (+k*pi*cos(k*pi*x-0.1).*sin(k*pi*y-0.2)) - 1i*eta*(sin(k*pi*x-0.1).*sin(k*pi*y-0.2)); ...
    @(x,y) (-k*pi*sin(k*pi*x-0.1).*cos(k*pi*y-0.2)) - 1i*eta*(sin(k*pi*x-0.1).*sin(k*pi*y-0.2)); ...
    @(x,y) (+k*pi*sin(k*pi*x-0.1).*cos(k*pi*y-0.2)) - 1i*eta*(sin(k*pi*x-0.1).*sin(k*pi*y-0.2))  ...
};

DBC = { ...
    @(x,y) (-k*pi*cos(k*pi*x-0.1).*sin(k*pi*y-0.2)); ...
    @(x,y) (+k*pi*cos(k*pi*x-0.1).*sin(k*pi*y-0.2)); ...
    @(x,y) (-k*pi*sin(k*pi*x-0.1).*cos(k*pi*y-0.2)); ...
    @(x,y) (+k*pi*sin(k*pi*x-0.1).*cos(k*pi*y-0.2))  ...
    };

poincareSteklovOperator = "DtN";

end