function [u_exact,rhs,c0,BC,IBC] = ItITest2(k)

bump = @(x,y) -1.5 * exp(-160. * ((x-0.5).^2 + (y-0.5).^2));
c0 = @(x,y) -k^2 * (1.0 - bump(x,y));
u_exact = @(x, y) exp(1i * k * x) .* cos(pi * y);
du_exactdx = @(x, y) 1i * k * exp(1i * k * x) .* cos(pi * y);
du_exactdy = @(x, y) -pi * exp(1i * k * x) .* sin(pi * y);
rhs = @(x, y) ( k^2 + (pi)^2 ) .* exp(1i * k * x) .* cos(pi * y) + c0(x,y) .* u_exact(x,y);
BC = {@(x,y) u_exact(x,y),...
      @(x,y) u_exact(x,y),...
      @(x,y) u_exact(x,y),...   
      @(x,y) u_exact(x,y),...
      @(x,y) u_exact(x,y)};
eta = k;
IBC = {@(x,y) -du_exactdx(x,y) + 1i*eta*u_exact(x,y),...
       @(x,y)  du_exactdx(x,y) + 1i*eta*u_exact(x,y),...
       @(x,y) -du_exactdy(x,y) + 1i*eta*u_exact(x,y),...
       @(x,y)  du_exactdy(x,y) + 1i*eta*u_exact(x,y)};

end